Book Store V1
ndayishimiyeeric/book-store pull request #5
Opened 2022-06-09 22:26 UTC by ndayishimiyeeric

### This PR has the following Features:

- Display a list of books.
- Add a book.
- Remove a selected book.
- Connect To API
- Styles

Happy Coding :smile_cat:

2022-06-09 23:11 UTC, Gambit142 requested changes
Hi @ndayishimiyeeric 👋, 

Good job so far!

## Highlights
- Good use of CSS module in components 💯 
- The UI design is identical to that of Zeplin's design

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- Kindly apply the changes I suggested in the comments below for all the CSS files used in the project especially for:
  - Form.module.css file
  - Navbar.module.css file 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- I noticed that I can not add a book more than once in your application. Whenever I try to add more books, I get this error in the console:

![image](https://user-images.githubusercontent.com/77106962/172959052-115c66a9-e285-4489-9262-c4d75cccb749.png)

Kindly fix it. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-09 23:11 UTC, Gambit142 commented on src/components/style/book.module.css
> +  display: flex;
- [ ] Great work styling your application. I noticed that you repeated this same rule `display: flex` a lot of times in this CSS file. It would be nice to put this rule in a selector and use it as a class on any JSX. Alternatively, you can use CSS variables to make it cleaner. You can read this [article](https://www.w3schools.com/css/css3_variables.asp) to have an idea of how to use CSS variables. 👍

2022-06-09 23:11 UTC, Gambit142 commented on src/components/style/book.module.css
> +
- [ ] I noticed that you repeated this same rule `color: #121212` a lot of times in this CSS file. It would be nice to put this rule in a selector and use it as a class on any JSX. Alternatively, you can use CSS variables to make it cleaner. You can read this [article](https://www.w3schools.com/css/css3_variables.asp) to have an idea of how to use CSS variables. 👍

2022-06-09 23:11 UTC, Gambit142 commented on src/components/style/book.module.css
> +  font-family: 'Roboto Slab', serif;
- [ ] I noticed that you repeated this same rule `font-family: 'Roboto Slab', serif;` a lot of times in this CSS file. It would be nice to put this rule in a selector and use it as a class on any JSX. Alternatively, you can use CSS variables to make it cleaner. You can read this [article](https://www.w3schools.com/css/css3_variables.asp) to have an idea of how to use CSS variables. 👍

2022-06-09 23:11 UTC, Gambit142 commented on src/components/style/book.module.css
> +    sans-serif;
- [ ] I noticed that you repeated this same rule `font-family: 'Montserrat', sans-serif;` a lot of times in this CSS file. It would be nice to put this rule in a selector and use it as a class on any JSX. Alternatively, you can use CSS variables to make it cleaner. You can read this [article](https://www.w3schools.com/css/css3_variables.asp) to have an idea of how to use CSS variables. 👍

2022-06-09 23:22 UTC, ndayishimiyeeric commented on src/components/style/book.module.css
> +  display: flex;
@Gambit142 I don't know what is the problem on your side but Adding a book is working On my side without erros And I can see a book that you've added

2022-06-10 06:59 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @ndayishimiyeeric**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Make sure that you used the correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). Therefore both - the main branch and the development branch should always be perfectly maintained. Any changes required in the application should be introduced in feature branches and approved before merging them to the development branch. Changes to the main branch can be merged only from the development branch and reviewed. 

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-10 07:42 UTC, merged